"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    NewType as typing___NewType,
    Optional as typing___Optional,
    Text as typing___Text,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

ActionTypeValue = typing___NewType('ActionTypeValue', builtin___int)
type___ActionTypeValue = ActionTypeValue
ActionType: _ActionType
class _ActionType(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[ActionTypeValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    ACTION_TYPE_DISCARD = typing___cast(ActionTypeValue, 0)
    ACTION_TYPE_TSUMOGIRI = typing___cast(ActionTypeValue, 1)
    ACTION_TYPE_RIICHI = typing___cast(ActionTypeValue, 2)
    ACTION_TYPE_CLOSED_KAN = typing___cast(ActionTypeValue, 3)
    ACTION_TYPE_ADDED_KAN = typing___cast(ActionTypeValue, 4)
    ACTION_TYPE_TSUMO = typing___cast(ActionTypeValue, 5)
    ACTION_TYPE_ABORTIVE_DRAW_NINE_TERMINALS = typing___cast(ActionTypeValue, 6)
    ACTION_TYPE_CHI = typing___cast(ActionTypeValue, 7)
    ACTION_TYPE_PON = typing___cast(ActionTypeValue, 8)
    ACTION_TYPE_OPEN_KAN = typing___cast(ActionTypeValue, 9)
    ACTION_TYPE_RON = typing___cast(ActionTypeValue, 10)
    ACTION_TYPE_NO = typing___cast(ActionTypeValue, 11)
    ACTION_TYPE_DUMMY = typing___cast(ActionTypeValue, 99)
ACTION_TYPE_DISCARD = typing___cast(ActionTypeValue, 0)
ACTION_TYPE_TSUMOGIRI = typing___cast(ActionTypeValue, 1)
ACTION_TYPE_RIICHI = typing___cast(ActionTypeValue, 2)
ACTION_TYPE_CLOSED_KAN = typing___cast(ActionTypeValue, 3)
ACTION_TYPE_ADDED_KAN = typing___cast(ActionTypeValue, 4)
ACTION_TYPE_TSUMO = typing___cast(ActionTypeValue, 5)
ACTION_TYPE_ABORTIVE_DRAW_NINE_TERMINALS = typing___cast(ActionTypeValue, 6)
ACTION_TYPE_CHI = typing___cast(ActionTypeValue, 7)
ACTION_TYPE_PON = typing___cast(ActionTypeValue, 8)
ACTION_TYPE_OPEN_KAN = typing___cast(ActionTypeValue, 9)
ACTION_TYPE_RON = typing___cast(ActionTypeValue, 10)
ACTION_TYPE_NO = typing___cast(ActionTypeValue, 11)
ACTION_TYPE_DUMMY = typing___cast(ActionTypeValue, 99)

EventTypeValue = typing___NewType('EventTypeValue', builtin___int)
type___EventTypeValue = EventTypeValue
EventType: _EventType
class _EventType(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[EventTypeValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    EVENT_TYPE_DISCARD = typing___cast(EventTypeValue, 0)
    EVENT_TYPE_TSUMOGIRI = typing___cast(EventTypeValue, 1)
    EVENT_TYPE_RIICHI = typing___cast(EventTypeValue, 2)
    EVENT_TYPE_CLOSED_KAN = typing___cast(EventTypeValue, 3)
    EVENT_TYPE_ADDED_KAN = typing___cast(EventTypeValue, 4)
    EVENT_TYPE_TSUMO = typing___cast(EventTypeValue, 5)
    EVENT_TYPE_ABORTIVE_DRAW_NINE_TERMINALS = typing___cast(EventTypeValue, 6)
    EVENT_TYPE_CHI = typing___cast(EventTypeValue, 7)
    EVENT_TYPE_PON = typing___cast(EventTypeValue, 8)
    EVENT_TYPE_OPEN_KAN = typing___cast(EventTypeValue, 9)
    EVENT_TYPE_RON = typing___cast(EventTypeValue, 10)
    EVENT_TYPE_DRAW = typing___cast(EventTypeValue, 12)
    EVENT_TYPE_RIICHI_SCORE_CHANGE = typing___cast(EventTypeValue, 13)
    EVENT_TYPE_NEW_DORA = typing___cast(EventTypeValue, 14)
    EVENT_TYPE_ABORTIVE_DRAW_FOUR_RIICHIS = typing___cast(EventTypeValue, 15)
    EVENT_TYPE_ABORTIVE_DRAW_THREE_RONS = typing___cast(EventTypeValue, 16)
    EVENT_TYPE_ABORTIVE_DRAW_FOUR_KANS = typing___cast(EventTypeValue, 17)
    EVENT_TYPE_ABORTIVE_DRAW_FOUR_WINDS = typing___cast(EventTypeValue, 18)
    EVENT_TYPE_EXHAUSTIVE_DRAW_NORMAL = typing___cast(EventTypeValue, 19)
    EVENT_TYPE_EXHAUSTIVE_DRAW_NAGASHI_MANGAN = typing___cast(EventTypeValue, 20)
EVENT_TYPE_DISCARD = typing___cast(EventTypeValue, 0)
EVENT_TYPE_TSUMOGIRI = typing___cast(EventTypeValue, 1)
EVENT_TYPE_RIICHI = typing___cast(EventTypeValue, 2)
EVENT_TYPE_CLOSED_KAN = typing___cast(EventTypeValue, 3)
EVENT_TYPE_ADDED_KAN = typing___cast(EventTypeValue, 4)
EVENT_TYPE_TSUMO = typing___cast(EventTypeValue, 5)
EVENT_TYPE_ABORTIVE_DRAW_NINE_TERMINALS = typing___cast(EventTypeValue, 6)
EVENT_TYPE_CHI = typing___cast(EventTypeValue, 7)
EVENT_TYPE_PON = typing___cast(EventTypeValue, 8)
EVENT_TYPE_OPEN_KAN = typing___cast(EventTypeValue, 9)
EVENT_TYPE_RON = typing___cast(EventTypeValue, 10)
EVENT_TYPE_DRAW = typing___cast(EventTypeValue, 12)
EVENT_TYPE_RIICHI_SCORE_CHANGE = typing___cast(EventTypeValue, 13)
EVENT_TYPE_NEW_DORA = typing___cast(EventTypeValue, 14)
EVENT_TYPE_ABORTIVE_DRAW_FOUR_RIICHIS = typing___cast(EventTypeValue, 15)
EVENT_TYPE_ABORTIVE_DRAW_THREE_RONS = typing___cast(EventTypeValue, 16)
EVENT_TYPE_ABORTIVE_DRAW_FOUR_KANS = typing___cast(EventTypeValue, 17)
EVENT_TYPE_ABORTIVE_DRAW_FOUR_WINDS = typing___cast(EventTypeValue, 18)
EVENT_TYPE_EXHAUSTIVE_DRAW_NORMAL = typing___cast(EventTypeValue, 19)
EVENT_TYPE_EXHAUSTIVE_DRAW_NAGASHI_MANGAN = typing___cast(EventTypeValue, 20)

class Score(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    round: builtin___int = ...
    honba: builtin___int = ...
    riichi: builtin___int = ...
    tens: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...

    def __init__(self,
        *,
        round : typing___Optional[builtin___int] = None,
        honba : typing___Optional[builtin___int] = None,
        riichi : typing___Optional[builtin___int] = None,
        tens : typing___Optional[typing___Iterable[builtin___int]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"honba",b"honba",u"riichi",b"riichi",u"round",b"round",u"tens",b"tens"]) -> None: ...
type___Score = Score

class Event(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    type: type___EventTypeValue = ...
    who: builtin___int = ...
    tile: builtin___int = ...
    open: builtin___int = ...

    def __init__(self,
        *,
        type : typing___Optional[type___EventTypeValue] = None,
        who : typing___Optional[builtin___int] = None,
        tile : typing___Optional[builtin___int] = None,
        open : typing___Optional[builtin___int] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"open",b"open",u"tile",b"tile",u"type",b"type",u"who",b"who"]) -> None: ...
type___Event = Event

class PublicObservation(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    game_id: typing___Text = ...
    player_ids: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text] = ...
    dora_indicators: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...

    @property
    def init_score(self) -> type___Score: ...

    @property
    def events(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Event]: ...

    def __init__(self,
        *,
        game_id : typing___Optional[typing___Text] = None,
        player_ids : typing___Optional[typing___Iterable[typing___Text]] = None,
        init_score : typing___Optional[type___Score] = None,
        dora_indicators : typing___Optional[typing___Iterable[builtin___int]] = None,
        events : typing___Optional[typing___Iterable[type___Event]] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"init_score",b"init_score"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"dora_indicators",b"dora_indicators",u"events",b"events",u"game_id",b"game_id",u"init_score",b"init_score",u"player_ids",b"player_ids"]) -> None: ...
type___PublicObservation = PublicObservation

class Hand(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    closed_tiles: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...
    opens: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...

    def __init__(self,
        *,
        closed_tiles : typing___Optional[typing___Iterable[builtin___int]] = None,
        opens : typing___Optional[typing___Iterable[builtin___int]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"closed_tiles",b"closed_tiles",u"opens",b"opens"]) -> None: ...
type___Hand = Hand

class PrivateObservation(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    who: builtin___int = ...
    draw_history: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...

    @property
    def init_hand(self) -> type___Hand: ...

    @property
    def curr_hand(self) -> type___Hand: ...

    def __init__(self,
        *,
        who : typing___Optional[builtin___int] = None,
        init_hand : typing___Optional[type___Hand] = None,
        draw_history : typing___Optional[typing___Iterable[builtin___int]] = None,
        curr_hand : typing___Optional[type___Hand] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"curr_hand",b"curr_hand",u"init_hand",b"init_hand"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"curr_hand",b"curr_hand",u"draw_history",b"draw_history",u"init_hand",b"init_hand",u"who",b"who"]) -> None: ...
type___PrivateObservation = PrivateObservation

class Observation(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    who: builtin___int = ...

    @property
    def public_observation(self) -> type___PublicObservation: ...

    @property
    def private_observation(self) -> type___PrivateObservation: ...

    @property
    def round_terminal(self) -> type___RoundTerminal: ...

    @property
    def legal_actions(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Action]: ...

    def __init__(self,
        *,
        who : typing___Optional[builtin___int] = None,
        public_observation : typing___Optional[type___PublicObservation] = None,
        private_observation : typing___Optional[type___PrivateObservation] = None,
        round_terminal : typing___Optional[type___RoundTerminal] = None,
        legal_actions : typing___Optional[typing___Iterable[type___Action]] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"private_observation",b"private_observation",u"public_observation",b"public_observation",u"round_terminal",b"round_terminal"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"legal_actions",b"legal_actions",u"private_observation",b"private_observation",u"public_observation",b"public_observation",u"round_terminal",b"round_terminal",u"who",b"who"]) -> None: ...
type___Observation = Observation

class Win(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    who: builtin___int = ...
    from_who: builtin___int = ...
    win_tile: builtin___int = ...
    fu: builtin___int = ...
    ten: builtin___int = ...
    ten_changes: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...
    yakus: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...
    fans: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...
    yakumans: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...
    ura_dora_indicators: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...

    @property
    def hand(self) -> type___Hand: ...

    def __init__(self,
        *,
        who : typing___Optional[builtin___int] = None,
        from_who : typing___Optional[builtin___int] = None,
        hand : typing___Optional[type___Hand] = None,
        win_tile : typing___Optional[builtin___int] = None,
        fu : typing___Optional[builtin___int] = None,
        ten : typing___Optional[builtin___int] = None,
        ten_changes : typing___Optional[typing___Iterable[builtin___int]] = None,
        yakus : typing___Optional[typing___Iterable[builtin___int]] = None,
        fans : typing___Optional[typing___Iterable[builtin___int]] = None,
        yakumans : typing___Optional[typing___Iterable[builtin___int]] = None,
        ura_dora_indicators : typing___Optional[typing___Iterable[builtin___int]] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"hand",b"hand"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"fans",b"fans",u"from_who",b"from_who",u"fu",b"fu",u"hand",b"hand",u"ten",b"ten",u"ten_changes",b"ten_changes",u"ura_dora_indicators",b"ura_dora_indicators",u"who",b"who",u"win_tile",b"win_tile",u"yakumans",b"yakumans",u"yakus",b"yakus"]) -> None: ...
type___Win = Win

class NoWinner(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    ten_changes: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...

    @property
    def tenpais(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___TenpaiHand]: ...

    def __init__(self,
        *,
        tenpais : typing___Optional[typing___Iterable[type___TenpaiHand]] = None,
        ten_changes : typing___Optional[typing___Iterable[builtin___int]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"ten_changes",b"ten_changes",u"tenpais",b"tenpais"]) -> None: ...
type___NoWinner = NoWinner

class TenpaiHand(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    who: builtin___int = ...

    @property
    def hand(self) -> type___Hand: ...

    def __init__(self,
        *,
        who : typing___Optional[builtin___int] = None,
        hand : typing___Optional[type___Hand] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"hand",b"hand"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"hand",b"hand",u"who",b"who"]) -> None: ...
type___TenpaiHand = TenpaiHand

class RoundTerminal(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    is_game_over: builtin___bool = ...

    @property
    def final_score(self) -> type___Score: ...

    @property
    def wins(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Win]: ...

    @property
    def no_winner(self) -> type___NoWinner: ...

    def __init__(self,
        *,
        final_score : typing___Optional[type___Score] = None,
        wins : typing___Optional[typing___Iterable[type___Win]] = None,
        no_winner : typing___Optional[type___NoWinner] = None,
        is_game_over : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"final_score",b"final_score",u"no_winner",b"no_winner"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"final_score",b"final_score",u"is_game_over",b"is_game_over",u"no_winner",b"no_winner",u"wins",b"wins"]) -> None: ...
type___RoundTerminal = RoundTerminal

class State(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def hidden_state(self) -> type___HiddenState: ...

    @property
    def public_observation(self) -> type___PublicObservation: ...

    @property
    def private_observations(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___PrivateObservation]: ...

    @property
    def round_terminal(self) -> type___RoundTerminal: ...

    def __init__(self,
        *,
        hidden_state : typing___Optional[type___HiddenState] = None,
        public_observation : typing___Optional[type___PublicObservation] = None,
        private_observations : typing___Optional[typing___Iterable[type___PrivateObservation]] = None,
        round_terminal : typing___Optional[type___RoundTerminal] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"hidden_state",b"hidden_state",u"public_observation",b"public_observation",u"round_terminal",b"round_terminal"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"hidden_state",b"hidden_state",u"private_observations",b"private_observations",u"public_observation",b"public_observation",u"round_terminal",b"round_terminal"]) -> None: ...
type___State = State

class HiddenState(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    game_seed: builtin___int = ...
    wall: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...
    ura_dora_indicators: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...

    def __init__(self,
        *,
        game_seed : typing___Optional[builtin___int] = None,
        wall : typing___Optional[typing___Iterable[builtin___int]] = None,
        ura_dora_indicators : typing___Optional[typing___Iterable[builtin___int]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"game_seed",b"game_seed",u"ura_dora_indicators",b"ura_dora_indicators",u"wall",b"wall"]) -> None: ...
type___HiddenState = HiddenState

class Action(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    game_id: typing___Text = ...
    who: builtin___int = ...
    type: type___ActionTypeValue = ...
    tile: builtin___int = ...
    open: builtin___int = ...

    def __init__(self,
        *,
        game_id : typing___Optional[typing___Text] = None,
        who : typing___Optional[builtin___int] = None,
        type : typing___Optional[type___ActionTypeValue] = None,
        tile : typing___Optional[builtin___int] = None,
        open : typing___Optional[builtin___int] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"game_id",b"game_id",u"open",b"open",u"tile",b"tile",u"type",b"type",u"who",b"who"]) -> None: ...
type___Action = Action
