[tool.black]
line-length = 88

# https://black.readthedocs.io/en/stable/compatible_configs.html
[flake8]  
max-line-length = 88
max-complexity = 18
ignore = ['E203', 'E501', 'W503']

# https://black.readthedocs.io/en/stable/compatible_configs.html
[tool.isort]  
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[mypy]
ignore_missing_imports = 1
