# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    NewType as typing___NewType,
    Optional as typing___Optional,
    Text as typing___Text,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

WindValue = typing___NewType('WindValue', builtin___int)
type___WindValue = WindValue
Wind: _Wind
class _Wind(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[WindValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    WIND_EAST = typing___cast(WindValue, 0)
    WIND_SOUTH = typing___cast(WindValue, 1)
    WIND_WEST = typing___cast(WindValue, 2)
    WIND_NORTH = typing___cast(WindValue, 3)
WIND_EAST = typing___cast(WindValue, 0)
WIND_SOUTH = typing___cast(WindValue, 1)
WIND_WEST = typing___cast(WindValue, 2)
WIND_NORTH = typing___cast(WindValue, 3)
type___Wind = Wind

AbsolutePosValue = typing___NewType('AbsolutePosValue', builtin___int)
type___AbsolutePosValue = AbsolutePosValue
AbsolutePos: _AbsolutePos
class _AbsolutePos(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[AbsolutePosValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    ABSOLUTE_POS_INIT_EAST = typing___cast(AbsolutePosValue, 0)
    ABSOLUTE_POS_INIT_SOUTH = typing___cast(AbsolutePosValue, 1)
    ABSOLUTE_POS_INIT_WEST = typing___cast(AbsolutePosValue, 2)
    ABSOLUTE_POS_INIT_NORTH = typing___cast(AbsolutePosValue, 3)
ABSOLUTE_POS_INIT_EAST = typing___cast(AbsolutePosValue, 0)
ABSOLUTE_POS_INIT_SOUTH = typing___cast(AbsolutePosValue, 1)
ABSOLUTE_POS_INIT_WEST = typing___cast(AbsolutePosValue, 2)
ABSOLUTE_POS_INIT_NORTH = typing___cast(AbsolutePosValue, 3)
type___AbsolutePos = AbsolutePos

RelativePosValue = typing___NewType('RelativePosValue', builtin___int)
type___RelativePosValue = RelativePosValue
RelativePos: _RelativePos
class _RelativePos(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[RelativePosValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    RELATIVE_POS_SELF = typing___cast(RelativePosValue, 0)
    RELATIVE_POS_RIGHT = typing___cast(RelativePosValue, 1)
    RELATIVE_POS_MID = typing___cast(RelativePosValue, 2)
    RELATIVE_POS_LEFT = typing___cast(RelativePosValue, 3)
RELATIVE_POS_SELF = typing___cast(RelativePosValue, 0)
RELATIVE_POS_RIGHT = typing___cast(RelativePosValue, 1)
RELATIVE_POS_MID = typing___cast(RelativePosValue, 2)
RELATIVE_POS_LEFT = typing___cast(RelativePosValue, 3)
type___RelativePos = RelativePos

ActionTypeValue = typing___NewType('ActionTypeValue', builtin___int)
type___ActionTypeValue = ActionTypeValue
ActionType: _ActionType
class _ActionType(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[ActionTypeValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    ACTION_TYPE_DISCARD = typing___cast(ActionTypeValue, 0)
    ACTION_TYPE_RIICHI = typing___cast(ActionTypeValue, 1)
    ACTION_TYPE_TSUMO = typing___cast(ActionTypeValue, 2)
    ACTION_TYPE_KAN_CLOSED = typing___cast(ActionTypeValue, 3)
    ACTION_TYPE_KAN_ADDED = typing___cast(ActionTypeValue, 4)
    ACTION_TYPE_KYUSYU = typing___cast(ActionTypeValue, 5)
    ACTION_TYPE_NO = typing___cast(ActionTypeValue, 6)
    ACTION_TYPE_CHI = typing___cast(ActionTypeValue, 7)
    ACTION_TYPE_PON = typing___cast(ActionTypeValue, 8)
    ACTION_TYPE_KAN_OPENED = typing___cast(ActionTypeValue, 9)
    ACTION_TYPE_RON = typing___cast(ActionTypeValue, 10)
ACTION_TYPE_DISCARD = typing___cast(ActionTypeValue, 0)
ACTION_TYPE_RIICHI = typing___cast(ActionTypeValue, 1)
ACTION_TYPE_TSUMO = typing___cast(ActionTypeValue, 2)
ACTION_TYPE_KAN_CLOSED = typing___cast(ActionTypeValue, 3)
ACTION_TYPE_KAN_ADDED = typing___cast(ActionTypeValue, 4)
ACTION_TYPE_KYUSYU = typing___cast(ActionTypeValue, 5)
ACTION_TYPE_NO = typing___cast(ActionTypeValue, 6)
ACTION_TYPE_CHI = typing___cast(ActionTypeValue, 7)
ACTION_TYPE_PON = typing___cast(ActionTypeValue, 8)
ACTION_TYPE_KAN_OPENED = typing___cast(ActionTypeValue, 9)
ACTION_TYPE_RON = typing___cast(ActionTypeValue, 10)
type___ActionType = ActionType

EventTypeValue = typing___NewType('EventTypeValue', builtin___int)
type___EventTypeValue = EventTypeValue
EventType: _EventType
class _EventType(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[EventTypeValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    EVENT_TYPE_DRAW = typing___cast(EventTypeValue, 0)
    EVENT_TYPE_DISCARD_FROM_HAND = typing___cast(EventTypeValue, 1)
    EVENT_TYPE_DISCARD_DRAWN_TILE = typing___cast(EventTypeValue, 2)
    EVENT_TYPE_RIICHI = typing___cast(EventTypeValue, 3)
    EVENT_TYPE_TSUMO = typing___cast(EventTypeValue, 4)
    EVENT_TYPE_RON = typing___cast(EventTypeValue, 5)
    EVENT_TYPE_CHI = typing___cast(EventTypeValue, 6)
    EVENT_TYPE_PON = typing___cast(EventTypeValue, 7)
    EVENT_TYPE_KAN_CLOSED = typing___cast(EventTypeValue, 8)
    EVENT_TYPE_KAN_OPENED = typing___cast(EventTypeValue, 9)
    EVENT_TYPE_KAN_ADDED = typing___cast(EventTypeValue, 10)
    EVENT_TYPE_NEW_DORA = typing___cast(EventTypeValue, 11)
    EVENT_TYPE_RIICHI_SCORE_CHANGE = typing___cast(EventTypeValue, 12)
    EVENT_TYPE_NO_WINNER = typing___cast(EventTypeValue, 13)
EVENT_TYPE_DRAW = typing___cast(EventTypeValue, 0)
EVENT_TYPE_DISCARD_FROM_HAND = typing___cast(EventTypeValue, 1)
EVENT_TYPE_DISCARD_DRAWN_TILE = typing___cast(EventTypeValue, 2)
EVENT_TYPE_RIICHI = typing___cast(EventTypeValue, 3)
EVENT_TYPE_TSUMO = typing___cast(EventTypeValue, 4)
EVENT_TYPE_RON = typing___cast(EventTypeValue, 5)
EVENT_TYPE_CHI = typing___cast(EventTypeValue, 6)
EVENT_TYPE_PON = typing___cast(EventTypeValue, 7)
EVENT_TYPE_KAN_CLOSED = typing___cast(EventTypeValue, 8)
EVENT_TYPE_KAN_OPENED = typing___cast(EventTypeValue, 9)
EVENT_TYPE_KAN_ADDED = typing___cast(EventTypeValue, 10)
EVENT_TYPE_NEW_DORA = typing___cast(EventTypeValue, 11)
EVENT_TYPE_RIICHI_SCORE_CHANGE = typing___cast(EventTypeValue, 12)
EVENT_TYPE_NO_WINNER = typing___cast(EventTypeValue, 13)
type___EventType = EventType

NoWinnerTypeValue = typing___NewType('NoWinnerTypeValue', builtin___int)
type___NoWinnerTypeValue = NoWinnerTypeValue
NoWinnerType: _NoWinnerType
class _NoWinnerType(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[NoWinnerTypeValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    NO_WINNER_TYPE_NORMAL = typing___cast(NoWinnerTypeValue, 0)
    NO_WINNER_TYPE_KYUUSYU = typing___cast(NoWinnerTypeValue, 1)
    NO_WINNER_TYPE_FOUR_RIICHI = typing___cast(NoWinnerTypeValue, 2)
    NO_WINNER_TYPE_THREE_RONS = typing___cast(NoWinnerTypeValue, 3)
    NO_WINNER_TYPE_FOUR_KANS = typing___cast(NoWinnerTypeValue, 4)
    NO_WINNER_TYPE_FOUR_WINDS = typing___cast(NoWinnerTypeValue, 5)
    NO_WINNER_TYPE_NM = typing___cast(NoWinnerTypeValue, 6)
NO_WINNER_TYPE_NORMAL = typing___cast(NoWinnerTypeValue, 0)
NO_WINNER_TYPE_KYUUSYU = typing___cast(NoWinnerTypeValue, 1)
NO_WINNER_TYPE_FOUR_RIICHI = typing___cast(NoWinnerTypeValue, 2)
NO_WINNER_TYPE_THREE_RONS = typing___cast(NoWinnerTypeValue, 3)
NO_WINNER_TYPE_FOUR_KANS = typing___cast(NoWinnerTypeValue, 4)
NO_WINNER_TYPE_FOUR_WINDS = typing___cast(NoWinnerTypeValue, 5)
NO_WINNER_TYPE_NM = typing___cast(NoWinnerTypeValue, 6)
type___NoWinnerType = NoWinnerType

class Score(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    round: builtin___int = ...
    honba: builtin___int = ...
    riichi: builtin___int = ...
    ten: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...

    def __init__(self,
        *,
        round : typing___Optional[builtin___int] = None,
        honba : typing___Optional[builtin___int] = None,
        riichi : typing___Optional[builtin___int] = None,
        ten : typing___Optional[typing___Iterable[builtin___int]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"honba",b"honba",u"riichi",b"riichi",u"round",b"round",u"ten",b"ten"]) -> None: ...
type___Score = Score

class Event(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    type: type___EventTypeValue = ...
    who: type___AbsolutePosValue = ...
    tile: builtin___int = ...
    open: builtin___int = ...

    def __init__(self,
        *,
        type : typing___Optional[type___EventTypeValue] = None,
        who : typing___Optional[type___AbsolutePosValue] = None,
        tile : typing___Optional[builtin___int] = None,
        open : typing___Optional[builtin___int] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"open",b"open",u"tile",b"tile",u"type",b"type",u"who",b"who"]) -> None: ...
type___Event = Event

class EventHistory(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def events(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Event]: ...

    def __init__(self,
        *,
        events : typing___Optional[typing___Iterable[type___Event]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"events",b"events"]) -> None: ...
type___EventHistory = EventHistory

class PrivateInfo(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    who: type___AbsolutePosValue = ...
    init_hand: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...
    draws: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...

    def __init__(self,
        *,
        who : typing___Optional[type___AbsolutePosValue] = None,
        init_hand : typing___Optional[typing___Iterable[builtin___int]] = None,
        draws : typing___Optional[typing___Iterable[builtin___int]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"draws",b"draws",u"init_hand",b"init_hand",u"who",b"who"]) -> None: ...
type___PrivateInfo = PrivateInfo

class Observation(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    player_ids: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text] = ...
    doras: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...
    who: type___AbsolutePosValue = ...

    @property
    def init_score(self) -> type___Score: ...

    @property
    def event_history(self) -> type___EventHistory: ...

    @property
    def private_info(self) -> type___PrivateInfo: ...

    @property
    def possible_actions(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Action]: ...

    def __init__(self,
        *,
        player_ids : typing___Optional[typing___Iterable[typing___Text]] = None,
        init_score : typing___Optional[type___Score] = None,
        doras : typing___Optional[typing___Iterable[builtin___int]] = None,
        event_history : typing___Optional[type___EventHistory] = None,
        who : typing___Optional[type___AbsolutePosValue] = None,
        private_info : typing___Optional[type___PrivateInfo] = None,
        possible_actions : typing___Optional[typing___Iterable[type___Action]] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"event_history",b"event_history",u"init_score",b"init_score",u"private_info",b"private_info"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"doras",b"doras",u"event_history",b"event_history",u"init_score",b"init_score",u"player_ids",b"player_ids",u"possible_actions",b"possible_actions",u"private_info",b"private_info",u"who",b"who"]) -> None: ...
type___Observation = Observation

class Win(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    who: type___AbsolutePosValue = ...
    from_who: type___AbsolutePosValue = ...
    closed_tiles: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...
    opens: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...
    win_tile: builtin___int = ...
    fu: builtin___int = ...
    ten: builtin___int = ...
    ten_changes: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...
    yakus: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...
    fans: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...
    yakumans: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...

    def __init__(self,
        *,
        who : typing___Optional[type___AbsolutePosValue] = None,
        from_who : typing___Optional[type___AbsolutePosValue] = None,
        closed_tiles : typing___Optional[typing___Iterable[builtin___int]] = None,
        opens : typing___Optional[typing___Iterable[builtin___int]] = None,
        win_tile : typing___Optional[builtin___int] = None,
        fu : typing___Optional[builtin___int] = None,
        ten : typing___Optional[builtin___int] = None,
        ten_changes : typing___Optional[typing___Iterable[builtin___int]] = None,
        yakus : typing___Optional[typing___Iterable[builtin___int]] = None,
        fans : typing___Optional[typing___Iterable[builtin___int]] = None,
        yakumans : typing___Optional[typing___Iterable[builtin___int]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"closed_tiles",b"closed_tiles",u"fans",b"fans",u"from_who",b"from_who",u"fu",b"fu",u"opens",b"opens",u"ten",b"ten",u"ten_changes",b"ten_changes",u"who",b"who",u"win_tile",b"win_tile",u"yakumans",b"yakumans",u"yakus",b"yakus"]) -> None: ...
type___Win = Win

class NoWinner(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    ten_changes: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...
    type: type___NoWinnerTypeValue = ...

    @property
    def tenpais(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___TenpaiHand]: ...

    def __init__(self,
        *,
        tenpais : typing___Optional[typing___Iterable[type___TenpaiHand]] = None,
        ten_changes : typing___Optional[typing___Iterable[builtin___int]] = None,
        type : typing___Optional[type___NoWinnerTypeValue] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"ten_changes",b"ten_changes",u"tenpais",b"tenpais",u"type",b"type"]) -> None: ...
type___NoWinner = NoWinner

class TenpaiHand(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    who: type___AbsolutePosValue = ...
    closed_tiles: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...

    def __init__(self,
        *,
        who : typing___Optional[type___AbsolutePosValue] = None,
        closed_tiles : typing___Optional[typing___Iterable[builtin___int]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"closed_tiles",b"closed_tiles",u"who",b"who"]) -> None: ...
type___TenpaiHand = TenpaiHand

class Terminal(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    is_game_over: builtin___bool = ...

    @property
    def final_score(self) -> type___Score: ...

    @property
    def wins(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Win]: ...

    @property
    def no_winner(self) -> type___NoWinner: ...

    def __init__(self,
        *,
        final_score : typing___Optional[type___Score] = None,
        wins : typing___Optional[typing___Iterable[type___Win]] = None,
        no_winner : typing___Optional[type___NoWinner] = None,
        is_game_over : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"final_score",b"final_score",u"no_winner",b"no_winner"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"final_score",b"final_score",u"is_game_over",b"is_game_over",u"no_winner",b"no_winner",u"wins",b"wins"]) -> None: ...
type___Terminal = Terminal

class State(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    player_ids: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text] = ...
    doras: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...
    wall: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...
    ura_doras: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int] = ...
    game_seed: builtin___int = ...

    @property
    def init_score(self) -> type___Score: ...

    @property
    def event_history(self) -> type___EventHistory: ...

    @property
    def private_infos(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___PrivateInfo]: ...

    @property
    def terminal(self) -> type___Terminal: ...

    def __init__(self,
        *,
        player_ids : typing___Optional[typing___Iterable[typing___Text]] = None,
        init_score : typing___Optional[type___Score] = None,
        doras : typing___Optional[typing___Iterable[builtin___int]] = None,
        event_history : typing___Optional[type___EventHistory] = None,
        wall : typing___Optional[typing___Iterable[builtin___int]] = None,
        ura_doras : typing___Optional[typing___Iterable[builtin___int]] = None,
        private_infos : typing___Optional[typing___Iterable[type___PrivateInfo]] = None,
        game_seed : typing___Optional[builtin___int] = None,
        terminal : typing___Optional[type___Terminal] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"event_history",b"event_history",u"init_score",b"init_score",u"terminal",b"terminal"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"doras",b"doras",u"event_history",b"event_history",u"game_seed",b"game_seed",u"init_score",b"init_score",u"player_ids",b"player_ids",u"private_infos",b"private_infos",u"terminal",b"terminal",u"ura_doras",b"ura_doras",u"wall",b"wall"]) -> None: ...
type___State = State

class Action(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    game_id: builtin___int = ...
    who: type___AbsolutePosValue = ...
    type: type___ActionTypeValue = ...
    discard: builtin___int = ...
    open: builtin___int = ...

    def __init__(self,
        *,
        game_id : typing___Optional[builtin___int] = None,
        who : typing___Optional[type___AbsolutePosValue] = None,
        type : typing___Optional[type___ActionTypeValue] = None,
        discard : typing___Optional[builtin___int] = None,
        open : typing___Optional[builtin___int] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"discard",b"discard",u"game_id",b"game_id",u"open",b"open",u"type",b"type",u"who",b"who"]) -> None: ...
type___Action = Action
