set namespaceSeparator ::


class cpp::mjproto::State <<(D,yellow) Data>> {

}

class cpp::mjproto::Observation <<(D,yellow) Data>> {

}

class python::mjproto::State <<(D,yellow) Data>> {

}

class python::mjproto::Observation <<(D,yellow) Data>> {

}

class json <<(D,lightblue) SerializedData>> {

}

class Tenhou::mjlog <<(D,lightblue) SerializedData>> {

}
note right
Visualizable in Tenhou Windows app
end note

object Features

cpp::mj::State -down-> cpp::mjproto::State
cpp::mj::State -> cpp::mj::Observation

cpp::mj::Observation -down-> cpp::mjproto::Observation

cpp::mjproto::State -up-> cpp::mj::State
cpp::mjproto::State -down-> json

cpp::mjproto::Observation -down-> json
cpp::mjproto::Observation -> Features

python::mjproto::State -down-> Tenhou::mjlog
python::mjproto::State -up-> json

python::mjproto::Observation -up-> json

Tenhou::mjlog -up-> python::mjproto::State

json -down-> python::mjproto::State
json -down-> python::mjproto::Observation
json -up-> cpp::mjproto::State
json -up-> cpp::mjproto::Observation