name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: sotetsuk/ubuntu-gcc-grpc:v0.0.4
    steps:
    - uses: actions/checkout@v2
    - name: Build mj
      run: |
        make build
    - name: Test mj
      run: |
        make test
    - name: Install mjconvert
      run: |
        cd mjconvert && make install
    - name: Test mjconvert (mjproto => mjlog)
      run: |
        cd mjconvert && make test-cli-mjproto-to-mjlog
