name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: sotetsuk/ubuntu-gcc-grpc:v0.0.2
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        ./build.sh
    - name: Run tests
      run: |
        ./build/test/mahjong_test
