name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache mjx/external
      uses: actions/cache@v2
      with:
        path: |
          mjx/external
        key: mjx-external-${{ hashFiles('mjx/cmake/*') }}

    - name: Build mjx
      run: make build -j 4 USE_SYSTEM_BOOST=OFF USE_SYSTEM_GRPC=OFF

    - name: Test mjx
      run: make test

