name: examples

on: [push,pull_request]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install
      run: cd examples && make install

    - name: Run checks
      run: cd examples && make checks

    - name: Run test
      run: cd examples && make test

