name: fmt

on: [push]

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        architecture: 'x64'
    - name: pip install 
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install black blackdoc isort
    - name: make pyfmt
      run: |
        make py-fmt
    - uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: '.'
        extensions: 'h,cpp'
        clangFormatVersion: 11
        style: google 
        inplace: True
    - uses: EndBug/add-and-commit@v4
      with:
        author_name: GitHub Actions
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
        message: 'Apply formatter'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
