# Copied from github.com/pybind/cmake_example
# Copyright (c) 2016 The Pybind Development Team, All rights reserved.
# https://github.com/pybind/cmake_example/blob/master/LICENSE

name: py

on:
  push:
  release:
    types:
      - published

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]  # [macos-latest, ubuntu-latest]
        python-version: ["3.9"]  #  ["2.7", "3.5", "3.8", "3.9"]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache external
        uses: actions/cache@v2
        with:
          path: |
            external
          key: external-${{ hashFiles('include/mjx/cmake/*') }}-${{ matrix.platform }}-v0

      - name: Add requirements
        run: python -m pip install --upgrade wheel setuptools

      - name: Build and install
        run: CMAKE_BUILD_PARALLEL_LEVEL=4 && python3 setup.py sdist && python3 setup.py install
      
      - name: Test
        run: python3 -m pip install pytest && make py-test

      - name: Run check
        run: python3 -m pip install -r requirements-dev.txt && make py-check

