# Copied from github.com/pybind/cmake_example
# Copyright (c) 2016 The Pybind Development Team, All rights reserved.
# https://github.com/pybind/cmake_example/blob/master/LICENSE

name: Wheels

on:
  push:
    branches:
      - master
  release:
    types:
      - published

env:
  CIBW_TEST_COMMAND: python3 -m pytest {project}/tests_py --import-mode=importlib 
  CIBW_TEST_EXTRAS: test


jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build SDist
      run: pipx run build --sdist

    - name: Check metadata
      run: pipx run twine check dist/*

    - uses: actions/upload-artifact@v2
      with:
        path: dist/*.tar.gz


  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-latest]  # [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: pypa/cibuildwheel@v1.12.0
      env:
        # Use manylinux2014 to use C++17 features
        # https://cibuildwheel.readthedocs.io/en/stable/options/#manylinux-image
        # https://cibuildwheel.readthedocs.io/en/stable/cpp_standards/#manylinux1-and-c14
        CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
        CIBW_MANYLINUX_I686_IMAGE: manylinux2014
        CIBW_MANYLINUX_PYPY_X86_64_IMAGE: manylinux2014
        CIBW_MANYLINUX_PYPY_I686_IMAGE: manylinux2014
        # To use C++17 features
        # https://cibuildwheel.readthedocs.io/en/stable/cpp_standards/#manylinux1-and-c14
        MACOSX_DEPLOYMENT_TARGET: "10.15"  # <filesystem> requires 10.15
        CIBW_BUILD: cp37-* cp38-* cp39-* cp310-* cp311-*   # cp37-* cp38-* cp39-* importlib.resources requires >= 3.7 
        CIBW_SKIP: pp* cp27-win* cp35-* cp36-* *win*
        # https://cibuildwheel.readthedocs.io/en/stable/options/#archs
        # universal2 arch raises this error:
        # CMake Error at mjx/external/grpc-src/third_party/boringssl-with-bazel/CMakeLists.txt:52 (message): Universal binaries not supported.
        # TODO: support Apple Silicon
        CIBW_ARCHS_MACOS: x86_64  #  auto universal2
        CIBW_TEST_SKIP: "*universal2:arm64"
        CIBW_TEST_EXTRAS: test
        CIBW_TEST_COMMAND: python3 -m pytest {project}/tests_py --import-mode=importlib 

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        path: wheelhouse/*.whl


  upload_all:
    name: Upload if release
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-22.04
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
    - uses: actions/setup-python@v2

    - uses: actions/download-artifact@v2
      with:
        name: artifact
        path: dist

    - uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
